# Generated by Django 4.0.1 on 2022-07-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
