# Generated by Django 4.0.4 on 2022-07-18 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='shop_images/%Y/')),
                ('password', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('creators', models.ManyToManyField(blank=True, related_name='Admins', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='Members', to=settings.AUTH_USER_MODEL)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tuman')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='products-img/')),
                ('image2', models.ImageField(upload_to='products-img/')),
                ('image3', models.ImageField(upload_to='products-img/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('count', models.IntegerField()),
                ('entry_price', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('validity_period', models.DateField(default='2006-04-02')),
                ('enterprise', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('seens', models.IntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
                ('typee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.types')),
            ],
        ),
    ]
