# Generated by Django 4.0.4 on 2022-07-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_activ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='creators',
            new_name='admins',
        ),
    ]
